# Generated by Django 5.1.5 on 2025-04-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=20)),
                ('dataInizio', models.DateField()),
                ('dataFine', models.DateField()),
                ('postiDisponibili', models.IntegerField()),
            ],
        ),
    ]
