# Generated by Django 5.1.5 on 2025-04-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatto',
            name='contenuto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contatto',
            name='cognome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contatto',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contatto',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
